assert.throws(TypeError, function() {
  for (const x of [1, 2, 3]) { x++ }
});